#!/tools/bin/bash
set +h
set -e

mkdir -pv $REALROOT_PT
cd $REALROOT_PT
mkdir -pv $REALROOT_PT/{bin,boot,proc,sys,etc/opt,home,lib,lib64,mnt,opt}
mkdir -pv $REALROOT_PT/{media/{floppy,cdrom},sbin,srv,var}                    
mkdir -pv $REALROOT_PT/usr/{,local/}{bin,include,lib,lib64,sbin,src}
mkdir -pv $REALROOT_PT/usr/{,local/}share/{doc,info,locale,man}
mkdir -v  $REALROOT_PT/usr/{,local/}share/{misc,terminfo,zoneinfo}
mkdir -v $REALROOT_PT/var/{lock,log,mail,run,spool}
mkdir -pv $REALROOT_PT/var/{opt,cache,lib/{misc,locate},local}
install -dv -m 0750 $REALROOT_PT/root
install -dv -m 1777 $REALROOT_PT/tmp $REALROOT_PT/var/tmp

cp -fv /usr/lib64/libgcc_s.so* $REALROOT_PT/usr/lib64
cp -fv /usr/lib64/libstdc++.so* $REALROOT_PT/usr/lib64
cp -fv /lib64/ld-linux-x86-64.so.2 $REALROOT_PT/lib64
cp -fv /lib64/libc.so* $REALROOT_PT/lib64
cp -fv /lib64/libm.so* $REALROOT_PT/lib64
cp -fv /lib64/libpthread.so* $REALROOT_PT/lib64
cp -fv /lib64/librt.so* $REALROOT_PT/lib64
cp -fv /lib64/libnss_* $REALROOT_PT/lib64
cp -fv /lib64/libcryp* $REALROOT_PT/lib64
cp -fv /lib64/libdl* $REALROOT_PT/lib64
cp -fv /lib64/libresolv.so* $REALROOT_PT/lib64
cp -fv /lib64/libutil.so* $REALROOT_PT/lib64

cd /glustersp/glustersp-commands/realroot/realroot-skel
find . | cpio -puvd $REALROOT_PT
exit