#!/bin/bash
set +h
set -e

cd $PKGDIR
sed -e 's@etc/adjtime@var/lib/hwclock/adjtime@g' \
    -i $(grep -rl '/etc/adjtime' .)
mkdir -pv /var/lib/hwclock
./configure --enable-arch --enable-partx --enable-write
make
make install DESTDIR=$REALROOT_PT
exit