#!/bin/bash
set +h
set -e

cd $PKGDIR
patch -Np1 -i ../binutils-2.18-configure-1.patch
mkdir -v ../binutils-build
cd ../binutils-build
CC="gcc -B/usr/bin/" ../binutils-2.18/configure \
    --prefix=/tools --disable-nls --disable-werror
make
make install
make -C ld clean
make -C ld LIB_PATH=/tools/lib
cp -v ld/ld-new /tools/bin
exit