#!/bin/bash
set +h
set -e

cd $PKGDIR
patch -Np1 -i ../binutils-2.18-configure-1.patch
mkdir -v ../binutils-build
cd ../binutils-build
../binutils-2.18/configure --prefix=/tools \
    --disable-nls --with-lib-path=/tools/lib
make
make install
make -C ld clean
make -C ld LIB_PATH=/usr/lib:/lib
cp -v ld/ld-new /tools/bin
exit