#!/bin/bash
set +h
set -e

cd $PKGDIR
patch -Np1 -i ../bash-3.2-fixes-8.patch
./configure --prefix=/tools --without-bash-malloc \
   ac_cv_func_working_mktime=yes
make
make tests
make install
ln -vs bash /tools/bin/sh
exit